layout(local_size_x = 64) in;

layout(std430, binding = 12) writeonly buffer OutputMatrices {
    mat4 finalPartMatrices[];
};

// Target the exact manual location from our Mixin
layout(location = 50) uniform uint totalInstancesCount;

const uint STRIDE = 24u;

vec4 slerp(vec4 v0, vec4 v1, float t) {
    v0 = normalize(v0);
    v1 = normalize(v1);
    float dotProduct = dot(v0, v1);

    if (dotProduct < 0.0) {
        v1 = -v1;
        dotProduct = -dotProduct;
    }

    if (dotProduct > 0.9995) {
        return normalize(mix(v0, v1, t));
    }

    float theta_0 = acos(dotProduct);
    float theta = theta_0 * t;
    float sin_theta = sin(theta);
    float sin_theta_0 = sin(theta_0);

    float s0 = cos(theta) - dotProduct * sin_theta / sin_theta_0;
    float s1 = sin_theta / sin_theta_0;
    return (s0 * v0) + (s1 * v1);
}

mat4 buildMatrix(vec3 pos, vec4 q, vec3 scale) {
    mat4 m;
    m[0][0] = (1.0 - 2.0 * (q.y * q.y + q.z * q.z)) * scale.x;
    m[0][1] = (2.0 * (q.x * q.y + q.w * q.z)) * scale.x;
    m[0][2] = (2.0 * (q.x * q.z - q.w * q.y)) * scale.x;
    m[0][3] = 0.0;

    m[1][0] = (2.0 * (q.x * q.y - q.w * q.z)) * scale.y;
    m[1][1] = (1.0 - 2.0 * (q.x * q.x + q.z * q.z)) * scale.y;
    m[1][2] = (2.0 * (q.y * q.z + q.w * q.x)) * scale.y;
    m[1][3] = 0.0;

    m[2][0] = (2.0 * (q.x * q.z + q.w * q.y)) * scale.z;
    m[2][1] = (2.0 * (q.y * q.z - q.w * q.x)) * scale.z;
    m[2][2] = (1.0 - 2.0 * (q.x * q.x + q.y * q.y)) * scale.z;
    m[2][3] = 0.0;

    m[3][0] = pos.x;
    m[3][1] = pos.y;
    m[3][2] = pos.z;
    m[3][3] = 1.0;
    return m;
}

mat4 getLocalMatrix(uint index, float t) {
    FlwInstance i = _flw_unpackInstance(0);

    vec3 mixedPos   = mix(i.posFrom,   i.posGoal,   t);
    vec4 mixedRot   = slerp(i.rotFrom, i.rotGoal,   t);
    vec3 mixedScale = mix(i.scaleFrom, i.scaleGoal, t);

    return buildMatrix(mixedPos, mixedRot, mixedScale);
}

void main() {
    uint idx = gl_GlobalInvocationID.x;

    // Completely bound-safe. Processes every uploaded part effortlessly.
    if (idx >= totalInstancesCount) return;

    float t = flw_partialTick;

        uint baseIdx   = idx;
        uint firstIdx  = idx + totalInstancesCount;
        uint secondIdx = idx + totalInstancesCount * 2;
        uint itemIdx   = idx + totalInstancesCount * 3;

        mat4 base   = getLocalMatrix(baseIdx,   flw_partialTick);
        mat4 first  = base   * getLocalMatrix(firstIdx,  flw_partialTick);
        mat4 second = first  * getLocalMatrix(secondIdx, flw_partialTick);
        mat4 item   = second * getLocalMatrix(itemIdx,   flw_partialTick);

        finalPartMatrices[0]   = base;
        finalPartMatrices[idx+1]  = first;
        finalPartMatrices[idx+2] = second;
        finalPartMatrices[idx+3]   = item;
}