package proto.mechanicalarmory.client.flywheel.slicer;

import dev.engine_room.flywheel.lib.model.part.InstanceTree;
import dev.engine_room.flywheel.api.instance.Instance;
import dev.engine_room.flywheel.api.visual.SectionTrackedVisual;
import net.minecraft.world.entity.Entity;
import net.minecraft.core.SectionPos;

import java.util.function.Consumer;

public class LightHelper {
    public static void light(InstanceTree tree, int packedLight) {
        if (tree != null) {
            tree.traverse(inst -> inst.light(packedLight).setChanged());
        }
    }

    public static void crumble(InstanceTree tree, Consumer<Instance> consumer) {
        if (tree != null) {
            tree.traverse(inst -> consumer.accept(inst));
        }
    }

    /**
     * Registers or updates the section-tracking collector for an entity visual.
     * Called from generated bytecode on both construction and each beginFrame so
     * that Flywheel always knows which chunk sections should trigger light updates.
     */
    public static void notifySections(SectionTrackedVisual.SectionCollector collector, Entity entity) {
        if (collector == null || entity == null) return;
        collector.sections(it.unimi.dsi.fastutil.longs.LongSet.of(
                SectionPos.asLong(entity.blockPosition())
        ));
    }
}
