package proto.mechanicalarmory.client.flywheel.slicer;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;

/**
 * Utility for defining and instantiating Flywheel Visual classes generated at runtime.
 */
public class VisualLoader extends ClassLoader {

    public VisualLoader(ClassLoader parent) {
        super(parent);
    }

    /**
     * Loads the raw generated bytecode into the JVM.
     *
     * @param className The internal name of the class (e.g. "proto.mechanicalarmory.client.flywheel.GeneratedChestVisual")
     * @param classBytes The bytecode generated by ASM ClassWriter
     * @return The loaded Class object
     */
    public Class<?> loadGeneratedClass(String className, byte[] classBytes) {
        // Convert internal ASM names (with slashes) to Java binary names (with dots)
        String binaryName = className.replace('/', '.');
        
        // Define the class in the JVM using our custom ClassLoader
        return defineClass(binaryName, classBytes, 0, classBytes.length);
    }

    /**
     * Instantiates the loaded visual using MethodHandles for extremely fast reflection-free creation.
     * 
     * @param loadedClass The class loaded by loadGeneratedClass
     * @return An instance of the generated class
     */
    public Object createInstance(Class<?> loadedClass) throws Throwable {
        MethodHandles.Lookup lookup = MethodHandles.publicLookup();
        // Assuming the generated class has a public no-arg constructor
        MethodHandle constructor = lookup.findConstructor(loadedClass, MethodType.methodType(void.class));
        return constructor.invoke();
    }
}
